/**
 * Orchestrate the spec commit flow:
 * 1. Create branch from default branch (or parent branch)
 * 2. Commit all spec files to the branch
 * 3. Create a PR
 */

import { prisma } from '../prisma'
import { branchNameFromCard } from './branchNaming'
import {
  getRef,
  createBranch,
  createOrUpdateFile,
  getFileContent,
  createPullRequest,
} from './githubClient'

export interface CommitResult {
  branchName: string
  prNumber: number
  prUrl: string
}

export async function commitFeatureSpecs(featureId: string): Promise<CommitResult> {
  const feature = await prisma.feature.findUnique({
    where: { id: featureId },
    include: {
      specs: true,
      team: { include: { product: true } },
      dependsOn: {
        include: { parent: true },
      },
    },
  })

  if (!feature) throw new Error('Feature not found')

  const { product } = feature.team
  const { owner, repoName, defaultBranch } = product

  // Determine base branch
  let baseBranch = defaultBranch

  // If feature depends on other features with branches, use parent branch
  const parentWithBranch = feature.dependsOn.find((d) => d.parent.specBranch)
  if (parentWithBranch?.parent.specBranch) {
    baseBranch = parentWithBranch.parent.specBranch
  }

  // Get base branch SHA
  const baseRef = await getRef(owner, repoName, baseBranch)
  if (!baseRef) throw new Error(`Base branch "${baseBranch}" not found`)
  const baseSha = baseRef.object.sha

  // Create spec branch
  const branchName = feature.specBranch ?? branchNameFromCard(feature.identifier, feature.title)

  // Try to create branch (may already exist)
  try {
    await createBranch(owner, repoName, branchName, baseSha)
  } catch {
    // Branch might already exist, that's fine
  }

  // Commit each spec file
  for (const spec of feature.specs) {
    // Check if file already exists on branch
    const existing = await getFileContent(owner, repoName, spec.filePath, branchName)
    const commitMsg = spec.isNew
      ? `Add spec: ${spec.filePath}`
      : `Update spec: ${spec.filePath}`

    await createOrUpdateFile(
      owner,
      repoName,
      spec.filePath,
      spec.content,
      commitMsg,
      branchName,
      existing?.sha,
    )
  }

  // Create PR if none exists
  let prNumber = feature.prNumber
  let prUrl = feature.prUrl

  if (!prNumber) {
    const specSummary = feature.specs.map((s) =>
      `- ${s.isNew ? 'New' : 'Updated'}: \`${s.filePath}\``,
    ).join('\n')

    const pr = await createPullRequest(
      owner,
      repoName,
      `[${feature.identifier}] ${feature.title} — Spec`,
      `## Spec for ${feature.identifier}: ${feature.title}\n\n${specSummary}\n\n_Generated by Workhorse_`,
      branchName,
      defaultBranch,
    )

    prNumber = pr.number
    prUrl = pr.html_url
  }

  // Update feature with branch and PR info
  await prisma.feature.update({
    where: { id: featureId },
    data: {
      specBranch: branchName,
      prNumber,
      prUrl,
      status: 'SPEC_COMPLETE',
    },
  })

  return {
    branchName,
    prNumber: prNumber!,
    prUrl: prUrl!,
  }
}
