/**
 * Orchestrate the spec commit flow:
 * 1. Check parent dependency commit ordering
 * 2. Create branch from default branch (or parent branch)
 * 3. Commit all spec files to the branch
 * 4. Create a PR
 * 5. Record activity
 */

import { prisma } from '../prisma'
import { branchNameFromCard } from './branchNaming'
import {
  getRef,
  createBranch,
  createOrUpdateFile,
  getFileContent,
  createPullRequest,
} from './githubClient'

export interface CommitResult {
  branchName: string
  prNumber: number
  prUrl: string
}

export async function commitCardSpecs(token: string, cardId: string): Promise<CommitResult> {
  const card = await prisma.card.findUnique({
    where: { id: cardId },
    include: {
      specs: true,
      team: { include: { project: true } },
      dependsOn: {
        include: { parent: true },
      },
    },
  })

  if (!card) throw new Error('Card not found')

  // Check parent dependency commit ordering
  const uncommittedParents = card.dependsOn
    .filter((d) => !d.parent.specBranch)
    .map((d) => d.parent.identifier)

  if (uncommittedParents.length > 0) {
    throw new Error(`Cannot commit: parent card(s) ${uncommittedParents.join(', ')} have not been committed yet`)
  }

  const { project } = card.team
  const { owner, repoName, defaultBranch } = project

  // Determine base branch
  let baseBranch = defaultBranch

  // If card depends on other cards with branches, use parent branch
  const parentWithBranch = card.dependsOn.find((d) => d.parent.specBranch)
  if (parentWithBranch?.parent.specBranch) {
    baseBranch = parentWithBranch.parent.specBranch
  }

  // Get base branch SHA
  const baseRef = await getRef(token, owner, repoName, baseBranch)
  if (!baseRef) throw new Error(`Base branch "${baseBranch}" not found`)
  const baseSha = baseRef.object.sha

  // Create spec branch
  const branchName = card.specBranch ?? branchNameFromCard(card.identifier, card.title)

  // Try to create branch (may already exist if this is a subsequent commit)
  try {
    await createBranch(token, owner, repoName, branchName, baseSha)
  } catch (err) {
    // Only tolerate "already exists" errors; re-throw anything else
    const message = err instanceof Error ? err.message : String(err)
    if (!message.includes('Reference already exists') && !message.includes('already exists')) {
      throw err
    }
  }

  // Commit each spec file
  for (const spec of card.specs) {
    // Check if file already exists on branch
    const existing = await getFileContent(token, owner, repoName, spec.filePath, branchName)
    const commitMsg = spec.isNew
      ? `Add spec: ${spec.filePath}`
      : `Update spec: ${spec.filePath}`

    await createOrUpdateFile(
      token,
      owner,
      repoName,
      spec.filePath,
      spec.content,
      commitMsg,
      branchName,
      existing?.sha,
    )

    // Track committed content for dirty detection
    await prisma.cardSpec.update({
      where: { id: spec.id },
      data: { committedContent: spec.content },
    })
  }

  // Create PR if none exists
  let prNumber = card.prNumber
  let prUrl = card.prUrl

  if (!prNumber) {
    const specSummary = card.specs.map((s) =>
      `- ${s.isNew ? 'New' : 'Updated'}: \`${s.filePath}\``,
    ).join('\n')

    const pr = await createPullRequest(
      token,
      owner,
      repoName,
      `[${card.identifier}] ${card.title} — Spec`,
      `## Spec for ${card.identifier}: ${card.title}\n\n${specSummary}\n\n_Generated by Workhorse_`,
      branchName,
      defaultBranch,
    )

    prNumber = pr.number
    prUrl = pr.html_url
  }

  // Update card with branch and PR info (do NOT set status)
  await prisma.card.update({
    where: { id: cardId },
    data: {
      specBranch: branchName,
      prNumber,
      prUrl,
    },
  })

  // Record committed activity
  await prisma.cardActivity.create({
    data: {
      cardId,
      action: 'committed',
      details: JSON.stringify({ branchName, prNumber, prUrl }),
    },
  })

  return {
    branchName,
    prNumber: prNumber!,
    prUrl: prUrl!,
  }
}
